title: XLPE ENGINEERING
logo: <img src="/assets/XLPE_LOGO.jpg" alt="XLPE Engineering Logo" style="max-width: 200px;">  
description: Electrical Contractor | Electrical Works
#show_downloads: true  
theme: jekyll-theme-slate
